<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Waters & Natural Hydration
            [
                'name' => 'AQUA Reflections Natural Still',
                'category' => 'Waters & Natural Hydration',
                'price' => 3.50,
                'dimensions' => '750 ml Glass Bottle',
                'material' => '100% Pure Mountain Spring Water',
                'description' => 'Bottled directly at the single protected source high in volcanic mountains. Crisp, naturally filtered through geological strata with balanced mineral composition.',
                'colors' => ['#0072CE', '#FAF8F3', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Evian French Alps Natural Spring Water',
                'category' => 'Waters & Natural Hydration',
                'price' => 4.20,
                'dimensions' => '1000 ml Eco Recycled Bottle',
                'material' => 'Natural Mineral Water from French Alps',
                'description' => 'Naturally slow-filtered through glacial rocks in the French Alps for over 15 years, delivering a uniquely balanced mineral electrolyte profile.',
                'colors' => ['#E57373', '#FAF8F3', '#90CAF9'],
                'featured' => true,
            ],
            [
                'name' => 'Volvic Touch of Fruit Lemon & Lime',
                'category' => 'Waters & Natural Hydration',
                'price' => 2.80,
                'dimensions' => '500 ml Recyclable Bottle',
                'material' => 'Volcanic Natural Spring Water, Organic Citrus Extract',
                'description' => 'Volcanic natural mineral water infused with a natural burst of organic lemon and lime essence. Refreshingly sugar-conscious with zero artificial preservatives.',
                'colors' => ['#DCE775', '#FAF8F3', '#81C784'],
                'featured' => false,
            ],
            [
                'name' => 'AQUA Sparkling Mineral Infusion',
                'category' => 'Waters & Natural Hydration',
                'price' => 3.75,
                'dimensions' => '380 ml Glass Bottle',
                'material' => 'Naturally Carbonated Spring Water, Fine Bubbles',
                'description' => 'Delicate, crisp effervescence combined with pristine mountain spring water. Crafted for premium dining pairings and palate cleansing.',
                'colors' => ['#0072CE', '#E0F7FA', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Danone Glacier Pure Electrolyte Water',
                'category' => 'Waters & Natural Hydration',
                'price' => 3.90,
                'dimensions' => '750 ml Aluminum Canteen',
                'material' => 'Sub-Arctic Glacier Water, Magnesium, Potassium',
                'description' => 'Sourced from ancient pristine sub-arctic aquifers, enriched with natural mineral electrolytes for enhanced cellular recovery and deep rehydration.',
                'colors' => ['#80DEEA', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],

            // Probiotic Dairy & Yogurt
            [
                'name' => 'Activia Probiotic Wild Strawberry',
                'category' => 'Probiotic Dairy & Yogurt',
                'price' => 4.50,
                'dimensions' => '4 x 125 g Pots (500 g Total)',
                'material' => 'Fermented Milk, Bifidus ActiRegularis, Wild Strawberry Compote',
                'description' => 'Creamy yogurt containing billions of exclusive live Bifidus cultures per serving to actively support digestive gut health and everyday vitality.',
                'colors' => ['#43A047', '#E91E63', '#FAF8F3'],
                'featured' => true,
            ],
            [
                'name' => 'Activia Zero Greek Style Natural Yogurt',
                'category' => 'Probiotic Dairy & Yogurt',
                'price' => 4.90,
                'dimensions' => '450 g Tub',
                'material' => 'Cultured Pasteurized Grade A Milk, 5 Live Probiotic Strains',
                'description' => 'Thick, velvety, and traditionally strained Greek style yogurt. Zero added sugar, naturally high in calcium, and rich in beneficial probiotics.',
                'colors' => ['#43A047', '#FAF8F3', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Danone Oikos Triple Zero Vanilla Greek Yogurt',
                'category' => 'Probiotic Dairy & Yogurt',
                'price' => 5.20,
                'dimensions' => '4 x 150 g Pots',
                'material' => 'Nonfat Strained Yogurt, Organic Madagascar Vanilla, Stevia Leaf',
                'description' => '15g complete protein per cup with 0g added sugar, 0% artificial sweeteners, and 0% fat. Perfect for high-performance breakfasts and fitness snacks.',
                'colors' => ['#1E88E5', '#FAF8F3', '#FFD54F'],
                'featured' => true,
            ],
            [
                'name' => 'Actimel Daily Immunity Shot Mixed Berries',
                'category' => 'Probiotic Dairy & Yogurt',
                'price' => 6.20,
                'dimensions' => '8 x 100 g Drinkable Bottles',
                'material' => 'Fermented Milk with L. Casei Danone, Vit D & B6, Berry Puree',
                'description' => 'A daily morning shot packed with 20 billion L. casei Danone probiotics, fortified with Vitamin D and B6 to bolster normal immune system defense.',
                'colors' => ['#E91E63', '#43A047', '#FAF8F3'],
                'featured' => true,
            ],
            [
                'name' => 'Danone Bio-Kefir Traditional Cultured Milk',
                'category' => 'Probiotic Dairy & Yogurt',
                'price' => 3.80,
                'dimensions' => '500 ml Glass Carafe',
                'material' => 'Organic Pasture Milk, 12 Authentic Live Kefir Grains',
                'description' => 'Slow-fermented for 24 hours according to heritage Danone methods. Pleasantly tangy, light, and teeming with beneficial live microorganisms.',
                'colors' => ['#7A8B6F', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],

            // Plant-Based Milks & Drinks
            [
                'name' => 'Alpro Barista Organic Oat Milk',
                'category' => 'Plant-Based Milks & Drinks',
                'price' => 3.60,
                'dimensions' => '1000 ml Tetra Brik',
                'material' => '100% European Organic Oats, Dipotassium Phosphate, Sea Salt',
                'description' => 'Engineered for specialty baristas and home espresso lovers. Produces a velvety, micro-textured froth that complements specialty coffee roasts.',
                'colors' => ['#D8C3A5', '#7A8B6F', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Alpro Roasted Almond Unsweetened Milk',
                'category' => 'Plant-Based Milks & Drinks',
                'price' => 3.75,
                'dimensions' => '1000 ml Tetra Brik',
                'material' => 'Mediterranean Roasted Almonds, Calcium Carbonate, Vit E',
                'description' => 'Subtly roasted Mediterranean almonds blended into a silky, light milk alternative. Zero sugar, only 13 kcal per 100ml, and naturally gluten-free.',
                'colors' => ['#D8C3A5', '#FAF8F3', '#8D6E63'],
                'featured' => true,
            ],
            [
                'name' => 'Silk Organic Creamy Soymilk',
                'category' => 'Plant-Based Milks & Drinks',
                'price' => 3.50,
                'dimensions' => '1000 ml Tetra Brik',
                'material' => 'Whole Harvested Non-GMO Organic Soybeans, Vit A & D2',
                'description' => 'Smooth, rich plant protein source delivering 8g of complete vegan protein per serving with essential amino acids and zero dairy lactose.',
                'colors' => ['#4CAF50', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],
            [
                'name' => 'Alpro Coconut & Almond Refresh Drink',
                'category' => 'Plant-Based Milks & Drinks',
                'price' => 3.90,
                'dimensions' => '1000 ml Tetra Brik',
                'material' => 'Young Coconut Milk, Crushed Sweet Almonds, Vitamin B12',
                'description' => 'An exotic blend of refreshing coconut water and creamy almonds. Naturally sweet, thirst-quenching, and perfect for tropical morning smoothies.',
                'colors' => ['#26C6DA', '#FAF8F3', '#D8C3A5'],
                'featured' => false,
            ],
            [
                'name' => 'Danone Cold-Pressed Golden Oat Latte',
                'category' => 'Plant-Based Milks & Drinks',
                'price' => 4.25,
                'dimensions' => '330 ml Glass Bottle',
                'material' => 'Gluten-Free Oats, Single Origin Arabica, Ceylon Cinnamon',
                'description' => 'Ready-to-drink artisanal cold brew blended with fresh oat milk and warm Danone warming spices. Clean energy with smooth sustained release.',
                'colors' => ['#A1887F', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],

            // Active & High Protein
            [
                'name' => 'Danone HiPRO 25g Protein Shake Chocolate',
                'category' => 'Active & High Protein',
                'price' => 3.95,
                'dimensions' => '330 ml Ergonomic Sport Bottle',
                'material' => 'Ultrafiltered Skimmed Milk, Whey Protein, Dutch Cocoa',
                'description' => 'Packed with 25g of high-quality dairy protein and BCAAs for post-workout muscle recovery. Lactose-free, fat-free, and no added sugars.',
                'colors' => ['#D32F2F', '#18181A', '#FAF8F3'],
                'featured' => true,
            ],
            [
                'name' => 'Danone HiPRO 20g Protein Pudding Caramel',
                'category' => 'Active & High Protein',
                'price' => 3.20,
                'dimensions' => '200 g Cup',
                'material' => 'Milk Protein Concentrate, Sea Salt Caramel Flavor, Stevia',
                'description' => 'An indulgent, velvety dessert-style protein snack with 20g protein per pot. Perfect treat to satisfy sweet cravings while supporting fitness goals.',
                'colors' => ['#FFB300', '#18181A', '#FAF8F3'],
                'featured' => false,
            ],
            [
                'name' => 'Danacol Plant Sterol Cardiovascular Shot',
                'category' => 'Active & High Protein',
                'price' => 7.50,
                'dimensions' => '6 x 100 g Bottles',
                'material' => 'Fermented Skimmed Milk, 1.6g Natural Plant Sterols, Citrus',
                'description' => 'Clinically proven to actively lower blood cholesterol by 7-10% in 2 to 3 weeks as part of a balanced diet and healthy active lifestyle.',
                'colors' => ['#C62828', '#FAF8F3', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Danone Clean Whey Recovery Strawberry Cream',
                'category' => 'Active & High Protein',
                'price' => 4.50,
                'dimensions' => '350 ml Glass Flask',
                'material' => 'Grass-Fed Native Whey Isolate, Real Strawberry Puree',
                'description' => 'Ultra-pure cold-filtered native whey isolate derived from grass-fed Scandinavian dairy cows. Rapid absorption with pristine clean taste.',
                'colors' => ['#F06292', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],
            [
                'name' => 'Danone Performance Electrolyte Fizz Tablets',
                'category' => 'Active & High Protein',
                'price' => 8.90,
                'dimensions' => '20 Effervescent Tablets Tube',
                'material' => 'Electrolyte Salts, Zinc, Magnesium Citrate, Vitamin C',
                'description' => 'Dissolves rapidly in pure water to replenish vital mineral ions lost through endurance sweat during sports, running, or outdoor cycling.',
                'colors' => ['#FF7043', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],

            // Healthy Snacks & Bowls
            [
                'name' => 'Artisanal Danone Honey Granola Crunch',
                'category' => 'Healthy Snacks & Bowls',
                'price' => 6.80,
                'dimensions' => '350 g Resealable Kraft Bag',
                'material' => 'Jumbo Rolled Oats, Raw Wildflower Honey, Pumpkin Seeds, Pecans',
                'description' => 'Slow-toasted in small batches with cold-pressed rapeseed oil and pure forest honey. Crisp, nutty, and fiber-rich companion for morning yogurt.',
                'colors' => ['#D8C3A5', '#7A8B6F', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Organic Acai Berry & Chia Breakfast Bowl',
                'category' => 'Healthy Snacks & Bowls',
                'price' => 5.40,
                'dimensions' => '220 g Ready-to-Eat Bowl with Spoon',
                'material' => 'Wild Amazonian Acai, Coconut Yogurt, Black Chia Seeds, Blueberries',
                'description' => 'Nutrient-rich ready-to-enjoy smoothie bowl packed with natural antioxidants, omega-3 fatty acids, and vibrant superfood vitality.',
                'colors' => ['#7B1FA2', '#FAF8F3', '#18181A'],
                'featured' => true,
            ],
            [
                'name' => 'Alpro Plant-Based Vanilla Soya Dessert',
                'category' => 'Healthy Snacks & Bowls',
                'price' => 3.20,
                'dimensions' => '4 x 125 g Pots',
                'material' => 'Hulled Organic Soybeans, Real Bourbon Vanilla Extract',
                'description' => 'A guilt-free 100% plant-based creamy dessert pot. Naturally low in saturated fat, easily digestible, and fortified with Vitamin B2 and B12.',
                'colors' => ['#FDD835', '#FAF8F3', '#795548'],
                'featured' => false,
            ],
            [
                'name' => 'Scandinavian Rye & Seed Crispbread',
                'category' => 'Healthy Snacks & Bowls',
                'price' => 4.10,
                'dimensions' => '250 g Box (18 Slices)',
                'material' => 'Stone-Ground Wholegrain Rye, Golden Flaxseed, Sesame Seeds',
                'description' => 'Traditional sourdough baked thin and crisp. Exceptional dietary fiber with low glycemic response, pairs delightfully with soft cheese or avocado.',
                'colors' => ['#8D6E63', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],
            [
                'name' => 'Danone Wild Lingonberry & Apple Compote',
                'category' => 'Healthy Snacks & Bowls',
                'price' => 5.20,
                'dimensions' => '280 g Glass Jar',
                'material' => 'Foraged Wild Lingonberries, Crisp Orchard Apples, Lemon',
                'description' => 'Hand-harvested in Danone boreal forests and gently simmered without refined sugar. Bright, tart, and rich in natural bioflavonoids.',
                'colors' => ['#D32F2F', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],

            // Specialized & Early Life
            [
                'name' => 'Bebelac Nutri-Step Toddler Formula 3',
                'category' => 'Specialized & Early Life',
                'price' => 14.50,
                'dimensions' => '800 g Sealed Metal Tin',
                'material' => 'Prebiotics FOS/GOS, Omega 3 & 6, 13 Essential Vitamins',
                'description' => 'Tailored nutritional support for active toddlers aged 1-3 years. Features an optimal prebiotic blend and iron to support happy growing tummies.',
                'colors' => ['#FFB300', '#0072CE', '#FAF8F3'],
                'featured' => true,
            ],
            [
                'name' => 'Aptamil Profutura Organic Follow-On Formula',
                'category' => 'Specialized & Early Life',
                'price' => 19.80,
                'dimensions' => '800 g Hermetic Safety Tin',
                'material' => 'Certified Organic Milk, Human Milk Oligosaccharide 2-FL, DHA',
                'description' => 'Our most advanced organic infant nutrition research formulation inspired by 50 years of breastmilk science. Free from artificial palm oil.',
                'colors' => ['#0288D1', '#FFD54F', '#FAF8F3'],
                'featured' => true,
            ],
            [
                'name' => 'Fortimel Plant-Based Complete Clinical Shake',
                'category' => 'Specialized & Early Life',
                'price' => 6.50,
                'dimensions' => '200 ml Clinical Bottle',
                'material' => 'Soy and Pea Protein, 28 Vitamins & Minerals, High Calorie',
                'description' => 'High-energy, high-protein oral nutritional supplement designed for dietary management of disease-related malnutrition and recovery.',
                'colors' => ['#388E3C', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],
            [
                'name' => 'Organic Puree Pouch Danone Pear & Raspberry',
                'category' => 'Specialized & Early Life',
                'price' => 2.40,
                'dimensions' => '100 g BPA-Free Pouch',
                'material' => '100% Demeter Certified Organic Pear, Summer Raspberries',
                'description' => 'Pure and smooth baby food puree for infants from 6 months. No added sugar, no artificial colorings, and zero fruit concentrates.',
                'colors' => ['#EC407A', '#FAF8F3', '#8BC34A'],
                'featured' => false,
            ],
            [
                'name' => 'Nutricia Neocate LCP Hypoallergenic Formula',
                'category' => 'Specialized & Early Life',
                'price' => 28.00,
                'dimensions' => '400 g Clinical Medical Can',
                'material' => '100% Free Amino Acids, LCPs, Nucleotides',
                'description' => 'Amino acid-based hypoallergenic medical formula for the dietary management of cow milk allergy and multiple food protein intolerances.',
                'colors' => ['#00796B', '#FAF8F3', '#18181A'],
                'featured' => false,
            ],
        ];

        $categoriesMap = Category::all()->keyBy('name');

        foreach ($products as $index => $item) {
            $catId = $categoriesMap[$item['category']]->id ?? 1;
            $stock = ($index % 8 === 0) ? 0 : rand(12, 60);

            Product::create([
                'category_id' => $catId,
                'name' => $item['name'],
                'slug' => Str::slug($item['name']),
                'description' => $item['description'],
                'material' => $item['material'],
                'dimensions' => $item['dimensions'],
                'colors' => $item['colors'],
                'price' => $item['price'],
                'stock' => $stock,
                'sku' => 'ND-' . strtoupper(Str::random(6)),
                'is_featured' => $item['featured'],
                'status' => 'active',
                'views_count' => rand(40, 600),
            ]);
        }
    }
}